### ISSUE TITLE
UI Lag

### ISSUE THREAD

**Issue by trini0n** [Foglio1024/Tera-custom-cooldowns#3] opened 2017-04-05 01:25 UTC
Especially prevalent in Harrowhold and raids, the UI will lag and stutter while trying to update. For example debuffs on p4 won't update live when you get them along with boss HP, character MP, etc.

Also the buff bar doesn't disappear when you tab out and stays wherever you placed it permanently.

**Comment by Foglio1024** [comment] 2017-04-05 01:42
Regarding buff bar not hiding when tabbing out, it's going to be fixed in next release. 

About the lag, I haven't found the cause which leads stuttering and freezes yet. Also I haven't tested buff bar in HH yet. Anyway, restarting TCC before starting the fight seems to help in some cases.

**Comment by trini0n** [comment] 2017-04-05 03:40
Mkay sounds good.

And yeah I found that it typically happens after having it running for a while, perhaps a memory issue too because my ShinraMeter will crash due to it freezing/stuttering. But yeah, the buff bar lagging is probably also directly due to the rest of the UI lagging alongside it.

I don't know if you've experienced it too but also using the tray icon to select click-through crashes TCC pretty often.

**Comment by Foglio1024** [comment] 2017-04-12 23:23
Buff bar not disappearing and crash on selecting click-thru fixed in v0.1.1.

**Closed** 2017-04-13 04:41 UTC
