### ISSUE TITLE
crashed

### ISSUE THREAD

**Issue by nando35x** [Foglio1024/Tera-custom-cooldowns#210] opened 2018-12-16 22:05 UTC
##### TCC v1.2.0 - 16/12/2018 14:03:26 #####
Version: 341702 - Region: THA - Server:1
Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at TCC.Parsing.MessageFactory.Process(ParsedMessage message) in D:\Repos\TCC\TCC.Core\Parsing\MessageFactory.cs:line 343
   at TCC.Parsing.PacketAnalyzer.PacketAnalysisLoop() in D:\Repos\TCC\TCC.Core\Parsing\PacketAnalyzer.cs:line 46
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
Source: mscorlib
Data: System.Collections.ListDictionaryInternal
InnerException: 
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at TCC.ViewModels.DashboardViewModel.<>c__DisplayClass66_0.<UpdateInventory>b__3(InventoryItem x) in D:\Repos\TCC\TCC.Core\ViewModels\DashboardViewModel.cs:line 510
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at TCC.ViewModels.DashboardViewModel.UpdateInventory() in D:\Repos\TCC\TCC.Core\ViewModels\DashboardViewModel.cs:line 510
   at TCC.Parsing.PacketHandler.HandleInventory(S_INVEN x) in D:\Repos\TCC\TCC.Core\Parsing\PacketHandler.cs:line 819
TargetSite: System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)

**Comment by Foglio1024** [comment] 2018-12-16 22:07
Duplicate of #208

**Closed by Foglio1024** 2018-12-16 22:07 UTC
