### ISSUE TITLE
Hard CPU loading

### ISSUE THREAD

**Issue by webstersama** [Foglio1024/Tera-custom-cooldowns#39] opened 2017-05-18 03:52 UTC
Hello. Have problem with lags while last version TCC started.
I seen this problem only on my core i5 CPU's. On core i7 i dont have lags.

**Comment by webstersama** [comment] 2017-05-18 03:55
I turned on only boss bar.

**Comment by Foglio1024** [comment] 2017-05-18 09:10
I can't fix this since I've received only few reports about this and I can't reproduce the issue myself to look into it. If it causes big issues you can always lower TCC priority using task manager.

Note: high CPU load is normal, specially in situations like guild/event bams.

**Comment by Foglio1024** [comment] 2017-05-20 23:59
Fixed in 0.4.5

**Closed by Foglio1024** 2017-05-20 23:59 UTC
