### ISSUE TITLE
Suggestions for improvement

### ISSUE THREAD

**Issue by webstersama** [Foglio1024/Tera-custom-cooldowns#4] opened 2017-04-10 06:22 UTC
**Character bar:**
1) loot options
2) party options
3) leave party button
4) debuff HP bar indicator

**Holding and saving position UI elements.**

**Will be nice to looks aggro indicator on boss HP.**

**Comment by Foglio1024** [comment] 2017-04-10 09:51
Suggestion 4 is already planned and will probably be added on next release. 

Suggestions 1, 2 and 3 are not possible for standalone app. They may be added when I'll port TCC as a plugin for Alkahest Tera proxy.

UI elements position should be already saved, but it's probably not working as intended; it will be fixed in next release.

Could you please explain better what do you mean with aggro indicator?

Thanks for your suggestions.

**Comment by webstersama** [comment] 2017-04-10 09:55
Yes, some UI elements save position, but only boss gauge not saved.
Hm.. if u get addro toward u, u'll see some icon on boss gauge like a enrage, and dont see if u lose aggro.

**Comment by webstersama** [comment] 2017-04-10 09:58
btw, Suggestions 1, 2 and 3 can be possible if some buttons will past and enter similar commands in chat.

**Comment by Foglio1024** [comment] 2017-04-12 23:24
TCC should now save position correctly in v0.1.1.

**Comment by LaraNotsil** [comment] 2017-04-13 20:54
5. shortcuts with your perfect design, maybe if it is possible more flexible, than just two double rows, like 12x3 and 12x1 sticky slots

**Comment by Foglio1024** [comment] 2017-04-13 21:14
That's a nice idea, but it would require a proxy to allow user interaction. All TCC can do is only gathering data and display it.

**Comment by LaraNotsil** [comment] 2017-04-13 21:44
I think, at least I hope, that ppl press skills not by mouse. And mostly just need the representation of cooldowns and shortcut button for an every slot in a bit better way. While there is no proxy injection it is possible just to preset you own pannel and then manage to stick you own by blocks.

Here is a smal representation of my words:
By color I separated Tera shortcut areas that give u similar TCC blocks (all black are single slots)
![image](https://cloud.githubusercontent.com/assets/21299150/25025214/0188f2ca-20aa-11e7-9275-b8d8311c1450.png)
So in TCC you will b able to make this:
![image](https://cloud.githubusercontent.com/assets/21299150/25025522/4bf6cc82-20ab-11e7-9a4e-8ae09b477e57.png)
(that is very usefrul if you have some Raser/Naga/Wolfking/Roccat e.t.c Mouse/Keyboards or just separate Alt/Shift/Ctrl comboes)

**Comment by webstersama** [comment] 2017-04-16 16:24
Pls make Hide/Unhide button.
And saving my choose for next TCC start.

**Comment by crvN** [comment] 2017-04-19 21:47
can you add potions, beer etc. to cooldown list?

**Comment by Foglio1024** [comment] 2017-04-19 22:13
I'll probably add those in a 3rd row. I'll do it when I'll separate images from main applications, since there are a lot of image icons and uploading them at each update would not be a perfect option.

**Comment by nagi666** [comment] 2017-04-21 00:03
When the debuff column of the boss HP bar becomes the second row, it will be halved.

**Comment by nagi666** [comment] 2017-04-21 00:03
When the debuff column of the boss HP bar becomes the second row, it will be halved.

**Comment by nagi666** [comment] 2017-04-21 00:04
When the debuff column of the boss HP bar becomes the second row, it will be halved.

**Comment by Foglio1024** [comment] 2017-04-21 00:07
It's a known issue already mentioned in the wiki.

**Comment by crvN** [comment] 2017-04-21 22:56
Сan you make separate hp bars if it's more than 1 boss, such as vergos 1st phase, so i can place them as i need?

**Comment by Foglio1024** [comment] 2017-04-21 23:10
That's a nice idea and it would help solving the clipped buffs issue in an easier way, but I was thinking about replacing normal boss bar with a specific window for HH ph1.

**Comment by fractured** [comment] 2017-04-24 13:31
Heya, wondering  if it's possible to configure TCC, so you can pick which direction the buff bar extends to. I kinda dont like using the buff bar atm because I'm so used to the buffs extending to the right and it doesnt fit my UI composition.

**Comment by Foglio1024** [comment] 2017-04-24 19:15
@fractured I'll keep that in mind for future updates. I'm focusing on some boss bars changes at the moment.

**Comment by Bernkastel-0** [comment] 2017-04-25 14:48
Static location CD bar please :D

**Comment by Foglio1024** [comment] 2017-04-25 17:03
@Bernkastel-0 you mean bar with fixed always-visible skills?

**Comment by Bernkastel-0** [comment] 2017-04-25 21:44
@Foglio1024 ya, fixed elements would be super useful

**Comment by Foglio1024** [comment] 2017-04-25 21:46
@Bernkastel-0 it would be a lot of work tho. It would require a different window for each class. Also it should be customizable and that would require even more work.

**Comment by webstersama** [comment] 2017-04-26 16:34
![tera_screenshot_20170318_223436](https://cloud.githubusercontent.com/assets/27190654/25445469/f1f97dd4-2ac7-11e7-9bf0-c2130b5a25d4.jpg)

Its my view of TCC skill bar

**Comment by Shikie** [comment] 2017-05-03 12:30
Any chance Valkyrie runemarks can be added the same way warrior edge is showing currently?

**Comment by Foglio1024** [comment] 2017-05-03 12:38
I'm thinking about adding a window with class-specific info, like static skill cooldowns indicators, runemarks/edge indicators, class buffs effects and cooldowns (like Deadly Gamble, Guardian Shout, Shadow Reaping, etc), maybe also info about amount of consumables in inventory (maybe with flashing icons when you're about to run out of nostrums or your bravery is off cooldown). I'm not sure if to do this extending the current character window (the one with hp/mp) or to make it a separate window. It will require quite some time though, since I'm the only one working on this.

**Comment by webstersama** [comment] 2017-05-05 08:09
New boss gauge bar too big... No enrage icon. Make possible using old design version. 
New UI boss is very uncomfortable.

Now i am stay on 0.2.2 ver.

**Comment by webstersama** [comment] 2017-05-10 06:17
![ukavw9iopz4](https://cloud.githubusercontent.com/assets/27190654/25885507/2baaccc2-3572-11e7-98f8-3cf272c730f5.jpg)

**Comment by crvN** [comment] 2017-05-16 12:15
When party member recieve debuff,  let his hp turned to purple.

**Comment by Foglio1024** [comment] 2017-05-16 21:42
![bar](https://cloud.githubusercontent.com/assets/18739596/26129285/e66d0e90-3a8f-11e7-8155-19daaae448bc.png)
A little update on the class-specific bar. I'm working on the skills part for now.

Top bar with dark border shows "main" skills (can be configured by the user). The user can choose to add some "secondary" skills under this bar. All other ignored skills, will be showed only when on cooldown in said second row (Marrow Brooch in the screenshot) next to the user-defined secondary skills.

The orange and gray bars with circles show Deadly Gamble's duration (orange) and cooldown (gray). They appear only when Deadly Gamble is used and slide from the right to the left for the duration of the buff/cooldown.

I'm planning to add edge (maybe an array of circles/rectangles changing color depending on current edge value), some indicator of current stance and maybe HP/MP/RE in order to replace CharacterWindow.

I think I will slowly release a basic implementation for all classes and then add more specific features in the future.

**Comment by KeioSeko** [comment] 2017-08-20 11:34
I like an idea of your latest brawler character window and glyph proc.

It would be nice to have something equal for **Slayer**, but with **OHS CD** info.
Guess, it's much easier to track resets of **OHS** with individual icon, because I can move and change size of this specific window.
![character_slayer](https://user-images.githubusercontent.com/31180272/29494481-f043e2e4-85b3-11e7-8aee-ae2bdcedcefc.jpg)

p.s. sorry for my english

**Comment by Foglio1024** [comment] 2017-08-20 13:05
It's a good idea. I don't play slayer so I have almost no idea about class mechanics and suggestions are welcome. I'll look into it and add this when I can.

**Comment by Mhoz** [comment] 2017-08-22 15:29
Really liking TCC and liked the last change on slayer (slayer main).
I would also like in addition to that (if possible): make ohs icon flash when it resets. Maybe add that to all skills that reset! 
Wanting to play tera with TCC in no UI mode since just Tera with UI runs slower than without UI + TCC, but my problem is that the default "x cooldown has been reset" (or whatever it says) from tera pops up before the skill would trigger cd if it hadn't reset*, whereas with TCC I have to wait to actually cast the skill to see if it went on cd or not, and that can often delay you. I don't know if this is due to limitations or whatever, just throwing some feedback :>
*Idk if that made sense, e.g.: if you wanted to, you could cancel ohs before it went on cd if you notice the popup hasn't... popped up... by rolling, casting early evis, ms, etc.

**Comment by Foglio1024** [comment] 2017-08-22 15:31
mmh, it should theorically already flash on resets. I'll give it a look and fix/add it.

**Comment by Mhoz** [comment] 2017-08-22 15:43
I think it flashes if it's a skill that goes on cd and the reset is triggered by another skill (ab, scattershot, rhk, casting icb, shadow reaping, etc)

**Comment by TeleTabs** [comment] 2017-10-26 16:02
Can place square icons would also be nice
individually move group people ...
Skills CD in min: sec

**Comment by Foglio1024** [comment] 2017-10-26 16:29
1. Won't be done
2. Could give it a try, but most likely I will not be able to do it in a reliable performant way
3. Won't be done as it would take too much space; I could find a workaround for it though
4. That's a nice idea, I could add a counter to the left side button

Thank you for your suggestions, post in this thread if you have more.

**Comment by TeleTabs** [comment] 2017-10-26 16:52
If the buttons were square, there would be more space for cd in Min: Sec
I understand that it would be a lot of work, thank you anyway! continue great work

**Comment by TeleTabs** [comment] 2017-11-01 18:36
Filter buffs in the healer group would help a lot!

**Comment by TeleTabs** [comment] 2017-11-02 06:39
Separate option to increase boss debuff numbers. Or leave them a little bigger.

**Comment by Yafity** [comment] 2018-05-20 11:39
1. Limit amount of shown enemy hp bars(e.g slider 1-20)
2. Add opportunity to make one window over other by clicking on it.

**Comment by Foglio1024** [comment] 2018-05-20 11:42
1. How do you decide which ones should be displayed?
2. I find it a bit difficult, considering how foreground windows are handled at the moment.

**Comment by Yafity** [comment] 2018-05-20 11:48
1. by range, agro or do you fight with it
2. can you do LFG over other windows?
3.
![image](https://user-images.githubusercontent.com/34633830/40278593-85e696c0-5c3c-11e8-86e1-e17bb4ff6db4.png)
4. add option to show all buffs(I need to select buffs but it's maybe my bad)

**Comment by Foglio1024** [comment] 2018-05-20 11:52
1. Those are already showed only if hit (or if the boss has a boss bar ingame)
2. LFG is not even forced in front of game. You could theorically open it once and alt-tab to it when needed. And the problem would be the same as I already said before.
3. Yea, forgot about that again.
4. You don't want to see ALL buffs, trust me :^)

**Comment by Yafity** [comment] 2018-05-20 12:13
![image](https://user-images.githubusercontent.com/34633830/40278659-130f928a-5c3e-11e8-89cf-f560d655c49e.png)
If I'm fighting with one boss, other hp bars stay there and needed bar can be in the corner. It's a pain to go by event location and see nothing but hp bars on the screen:(

**Comment by Yafity** [comment] 2018-05-22 18:37
2. when party is changed(joining, inviting etc) LFG list is opened
3. I mean when you click on chat tag(global, trade, party...) you change chat
4. When several people apply only first of them shown in apply chat(spotted just now)

**Comment by Foglio1024** [comment] 2018-05-22 18:46
2. Nothing to fix, you have to replace PartyBoardMemberInfo.gpk with empty file (or check your settings if you're not using TCC LFG window)
3. Won't be done
4. That's because of spam filter, I'll see if I can make a workaround for it

**Comment by Foglio1024** [comment] 2018-05-22 18:55
The LFG you're in will have yellow message and it will have a "Refresh" button instead of "Apply". Applicants list will be showed inside the LFG itself, under the current party members list.

**Comment by Yafity** [comment] 2018-05-23 15:57
![image](https://user-images.githubusercontent.com/34633830/40436130-f8e7126e-5eba-11e8-814e-0cfa05713b5b.png)
can't inspect, player menu doesn't appear

**Comment by Zoananh** [comment] 2018-07-25 16:22
discord notification doesn`t work for me or at least when i tried to send test message i got "Failed to execute Discord webhook"

**Comment by Foglio1024** [comment] 2018-07-25 16:47
You either copied a wrong webhook URL or you inserted some invalid character in the notification message.

**Comment by Delaene** [comment] 2018-08-30 20:21
1- As already asked by Yafity, is there a chance to have a "lock window position" option, and make it so that when you lock a window its bar (the one with the hide-always show-dim options) disappear? I keep some windows close to each other and when i hover on one, the bar i mentioned before appears on another window. This would also make it so that you don't move windows by accident.
![image](https://user-images.githubusercontent.com/42815462/44876964-d4d1d180-aca2-11e8-9076-beaa0e565c7c.png)
2- Is it possible to have an option to show party in the "classic" vertical mode, maybe retaining the "1st tank, 2nd healer then dps" list style?

**Comment by Foglio1024** [comment] 2018-09-09 19:27
Done last request in v1.1.11. Closing this as it's getting too messy. Reopen individual issues if needed.

**Closed by Foglio1024** 2018-09-09 19:27 UTC
Labels: enhancement
